BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `STUDENTS` (
	`ID`	INTEGER NOT NULL UNIQUE,
	`NAME`	TEXT,
	`EMAIL`	TEXT UNIQUE,
	`CAREER`	TEXT,
	`HASH`	TEXT,
	`TYPE`	INTEGER DEFAULT 1,
	PRIMARY KEY(`ID`)
);
INSERT INTO `STUDENTS` VALUES (201228433,'ERICK','eguicoro2@gmail.com','ING. COMPUTADORES','123',1);
INSERT INTO `STUDENTS` VALUES (201228434,'JUAN','werwe','werwe','123',1);
COMMIT;
