version: "3"
services:
  news-service:
    # replace username/repo:tag with your name and image details
    image: darkventus/news-service
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
  users-service:
    # replace username/repo:tag with your name and image details
    image: darkventus/users-service
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "3001:3001"
  sports-service:
    # replace username/repo:tag with your name and image details
    image: darkventus/sports-service
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "3002:3002"
  visualizer-service:
    # replace username/repo:tag with your name and image details
    image: dockersamples/visualizer
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "3003:8080"
  update-service:
    # replace username/repo:tag with your name and image details
    image: jenkinsci/blueocean
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "3004:8080"