http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  news-api:
    host: localhost
    paths: '/news'
  sports-api:
    host: localhost
    paths: '/sports'
  users-api:
    host: localhost
    paths: '/users'
serviceEndpoints:
  news-service:
    #url: 'http://192.168.99.100:5001/graphiql'
    url: 'http://localhost:3000/graphiql?query=%7B%20allNews%7B%0A%20%20_id%2C%0A%20%20title%0A%20%20subtitle%0A%20%20sport%0A%09%7D%20%0A%7D'
  sports-service:
    url: 'http://localhost:3002/graphiql'
    #url: 'http://192.168.99.100:5002/graphiql'
  users-service:
    url: 'http://localhost:3001/graphiql'
    #url: 'http://192.168.99.100:5003/graphiql'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  news-api:
    apiEndpoints:
      - news-api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: news-service
              changeOrigin: true
  sports-api:
    apiEndpoints:
      - sports-api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: sports-service
              changeOrigin: true
  users-api:
    apiEndpoints:
      - users-api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: users-service
              changeOrigin: true
#0wYrq8qviIuoE9XtQTeajt:69JYalBgTgcQEY9nAEyCWV