http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  news-api:
    host: localhost
    paths: '/news/'
serviceEndpoints:
  news-service:
    #url: 'http://192.168.99.100:5001/graphiql'
    url: 'http://localhost:3000/graphiql'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - news-api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: news-service 
              changeOrigin: true
